### ISSUE TITLE
The "Add all" function is not working.

### ISSUE THREAD

**Issue by JulioPradera** [shagabutdinov/sublime-semicolon#3]
When I use the "Add" function the semicolon is inserted normally. However, when I use the "Add all" function, both via the shortcut (`alt+shift+w`) and the Command Palette, nothing happens.
The following message appears on the console:

> command: add_semicolon_to_statements
Traceback (most recent call last):
File "D:\Sublime Text\sublime_plugin.py", line 1088, in run_
return self.run(edit)
File "D:\Sublime Text\Data\Installed Packages\Semicolon.sublime-package\commands.py", line 14, in run
File "D:\Sublime Text\Data\Installed Packages\Semicolon.sublime-package\semicolon.py", line 103, in add_all
AttributeError: 'module' object has no attribute 'errors'

**Comment by shagabutdinov** [comment]
Hey, the default way of formatting code (and adding semicolons) is [prettier](https://prettier.io/) these days. I've switched to it a while ago and it works much better than a tool written in 2 hours :) Can I suggest you trying prettier?

**Comment by JulioPradera** [comment]
It is really sad to know that.
I had already tested the JsPrettier plugin, but I didn't like it very much.
I use the portable version of Sublime Text, as I constantly need to edit scripts on different computers. To use the JsPrettier plugin I always need to be installing Node.js and Prettier. In addition, it forces me to always save the script in order to format it, and sometimes I just need to copy a code and format it to be able to debug it. For this reason, I prefer to use the JsFormat plugin (even though it doesn't add semicolons).
If I could use JsFormat and this plugin together, linked by Chain of Command, I believe it would be a much more elegant and independent solution. :)
